[tool.pyright]
stubPath = "stubs"

reportMissingImports = true
reportMissingTypeStubs = true

pythonVersion = "3.10"
pythonPlatform = "Linux"

[tool.mypy]
warn_unused_configs = true
ignore_missing_imports = true
warn_incomplete_stub = false
