from typing import Any, ClassVar

IS_PY3K: bool
randint: method

class SequenceMatcher:
    __init__: ClassVar[function] = ...
    _SequenceMatcher__chain_b: ClassVar[function] = ...
    find_longest_match: ClassVar[function] = ...
    get_grouped_opcodes: ClassVar[function] = ...
    get_matching_blocks: ClassVar[function] = ...
    get_opcodes: ClassVar[function] = ...
    quick_ratio: ClassVar[function] = ...
    ratio: ClassVar[function] = ...
    real_quick_ratio: ClassVar[function] = ...
    set_seq1: ClassVar[function] = ...
    set_seq2: ClassVar[function] = ...
    set_seqs: ClassVar[function] = ...
    @classmethod
    def __class_getitem__(cls, *args, **kwargs) -> Any: ...

class median:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def finalize(self, *args, **kwargs) -> Any: ...
    def step(self, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_median(*args, **kwargs) -> Any: ...
def damerau_levenshtein_dist(*args, **kwargs) -> Any: ...
def levenshtein_dist(*args, **kwargs) -> Any: ...
def str_dist(*args, **kwargs) -> Any: ...
