from peewee import *
from _typeshed import Incomplete
from peewee import BooleanField as _BooleanField, DateField as _DateField, DateTimeField as _DateTimeField, DecimalField as _DecimalField, TimeField as _TimeField
from playhouse.sqlite_ext import SqliteExtDatabase as SqliteExtDatabase

class APSWDatabase(SqliteExtDatabase):
    server_version: Incomplete
    def __init__(self, database, **kwargs) -> None: ...
    def register_module(self, mod_name, mod_inst) -> None: ...
    def unregister_module(self, mod_name) -> None: ...
    def load_extension(self, extension) -> None: ...
    def last_insert_id(self, cursor, query_type: Incomplete | None = ...): ...
    def rows_affected(self, cursor): ...
    def begin(self, lock_type: str = ...) -> None: ...
    def commit(self): ...
    def rollback(self): ...
    def execute_sql(self, sql, params: Incomplete | None = ..., commit: bool = ...): ...

def nh(s, v): ...

class BooleanField(_BooleanField):
    def db_value(self, v): ...

class DateField(_DateField):
    db_value: Incomplete

class TimeField(_TimeField):
    db_value: Incomplete

class DateTimeField(_DateTimeField):
    db_value: Incomplete

class DecimalField(_DecimalField):
    db_value: Incomplete
