from _typeshed import Incomplete
from peewee import MySQLDatabase, TextField

class MySQLConnectorDatabase(MySQLDatabase):
    def cursor(self, commit: Incomplete | None = ...): ...

class MariaDBConnectorDatabase(MySQLDatabase):
    def cursor(self, commit: Incomplete | None = ...): ...
    def last_insert_id(self, cursor, query_type: Incomplete | None = ...): ...

class JSONField(TextField):
    field_type: str
    def db_value(self, value): ...
    def python_value(self, value): ...

def Match(columns, expr, modifier: Incomplete | None = ...): ...
