from peewee import *
from _typeshed import Incomplete
from playhouse.sqlite_ext import SqliteExtDatabase as SqliteExtDatabase

__sqlcipher_version__: Incomplete

class _SqlCipherDatabase:
    server_version: Incomplete
    def set_passphrase(self, passphrase) -> None: ...
    def rekey(self, passphrase): ...

class SqlCipherDatabase(_SqlCipherDatabase, SqliteDatabase): ...
class SqlCipherExtDatabase(_SqlCipherDatabase, SqliteExtDatabase): ...
